### ISSUE TITLE
Server fails to start [1.16.5]

### ISSUE THREAD

**Issue by HockeyZman2000** [CorgiTaco/Enhanced-Celestials#10]
Server Log: https://pastebin.com/3X51AKzS

When attempting to start the server, reports an error from Enhanced Celestials with no crash report. Not quite sure what is happening, any help would be appreciated!

**Comment by pjlasl** [comment]
I am seeing the same thing: https://pastebin.com/LqtAPncS

**Comment by Scorchyskull** [comment]
Tried booting it on my own server and I'm getting the same exact error

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/3209225

**Comment by pjlasl** [comment]
I was able to load without incident.
