### ISSUE TITLE
1.16.5 Crash (Unknown Problem,Forge/36.2.20)

### ISSUE THREAD

**Issue by AmyRose1288** [CorgiTaco/Enhanced-Celestials#100]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/26/22 4:44 PM
Description: Exception in server tick loop

java.lang.RuntimeException: null
	at corgitaco.enhancedcelestials.LunarContext$$Lambda$8003/1347361116.get(Unknown Source) ~[?:?] {}
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51] {}
	at corgitaco.enhancedcelestials.LunarContext.readOrCreateConfigJson(LunarContext.java:365) ~[?:2.0.9-1.16.5] {re:mixin,re:classloading}
	at corgitaco.enhancedcelestials.LunarContext.<init>(LunarContext.java:72) ~[?:2.0.9-1.16.5] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerWorld.handler$zcm000$injectLunarContext(ServerWorld.java:1539) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorld.java:205) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:375) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:60) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:inventorypause.mixins.json:IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$7879/1908506135.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1389996712 bytes (1325 MB) / 2219835392 bytes (2117 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.16.0
	Mod List: 
		secondchanceforge-1.2.0.jar                       |Second Chance Forge           |secondchanceforge             |1.2.0               |DONE      |Manifest: NOSIGNATURE
		justenoughbeacons-3.1-1.16.3.jar                  |Just Enough Beacons           |justenoughbeacons             |3.1-1.16.3          |DONE      |Manifest: NOSIGNATURE
		zombiehorsespawn_1.16.5-3.0.jar                   |Zombie Horse Spawn            |zombiehorsespawn              |3.0                 |DONE      |Manifest: NOSIGNATURE
		superflatworldnoslimes_1.16.5-1.4.jar             |Superflat World No Slimes     |superflatworldnoslimes        |1.4                 |DONE      |Manifest: NOSIGNATURE
		findme-1.16.3-2.2.1.0.jar                         |Find Me                       |findme                        |2.2.1               |DONE      |Manifest: NOSIGNATURE
		villagerdeathmessages_1.16.5-2.1.jar              |Villager Death Messages       |villagerdeathmessages         |2.1                 |DONE      |Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |Manifest: NOSIGNATURE
		Controlling-7.0.0.28.jar                          |Controlling                   |controlling                   |7.0.0.28            |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.31.jar                |Bookshelf                     |bookshelf                     |10.4.31             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		GildingMod-FIXED.jar                              |Gilding                       |gilding                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		cheat_mode-1.16.X-1.2.3.jar                       |Cheat Mode Mod                |cheat_mode                    |1.2.3               |DONE      |Manifest: NOSIGNATURE
		ChanceCubes-1.16.5-5.0.2.433.jar                  |Chance Cubes                  |chancecubes                   |1.16.5-5.0.2.433    |DONE      |Manifest: NOSIGNATURE
		potionstacker_1.16.5-1.0.jar                      |Potion Stacker Mod            |potionstacker                 |1.0                 |DONE      |Manifest: NOSIGNATURE
		jeed-1.16.5-1.6.jar                               |Just Enough Effect Description|jeed                          |1.16.5-1.6          |DONE      |Manifest: NOSIGNATURE
		skeletonhorsespawn_1.16.5-1.9.jar                 |Skeleton Horse Spawn          |skeletonhorsespawn            |1.9                 |DONE      |Manifest: NOSIGNATURE
		zombievillagersfromspawner_1.16.5-1.5.jar         |Zombie Villagers From Spawner |zombievillagersfromspawner    |1.5                 |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.133.jar         |Just Enough Resources         |jeresources                   |0.12.1.133          |DONE      |Manifest: NOSIGNATURE
		PeanutCraft-1.16.5-1.0.1.jar                      |PeanutCraft                   |peanutcraft                   |1.0.1               |DONE      |Manifest: NOSIGNATURE
		ninjaphenix-container-library-1.2.10+1.16.5.jar   |NinjaPhenix's Container Librar|ninjaphenix_container_lib     |1.2.10              |DONE      |Manifest: NOSIGNATURE
		mineralchance_1.16.5-1.6.jar                      |Mineral Chance                |mineralchance                 |1.6                 |DONE      |Manifest: NOSIGNATURE
		anviltooltipmod-MC1.16.3-1.0.0.jar                |Anvil Tooltip Mod             |anviltooltipmod               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		betterspawnercontrol_1.16.5-1.5.jar               |Better Spawner Control        |betterspawnercontrol          |1.5                 |DONE      |Manifest: NOSIGNATURE
		visiblearmorslots-2.0-1.16.5.jar                  |Visible Armor Slots           |visiblearmorslots             |2.0-1.16.5          |DONE      |Manifest: NOSIGNATURE
		EditSign-1.16.5-2.2.1.jar                         |EditSign                      |editsign                      |2.2.1               |DONE      |Manifest: NOSIGNATURE
		edibles_1.16.5-2.4.jar                            |Edibles                       |edibles                       |2.4                 |DONE      |Manifest: NOSIGNATURE
		StumbleUponCampsites.jar                          |StumbleUponCamps              |stumbleuponcamps              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		fishontheline_1.16.5-1.3.jar                      |Fish On The Line              |fishontheline                 |1.3                 |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		BasaltWalker-1.16.5-1.3.1.jar                     |Basalt Walker                 |basalt_walker                 |1.3.1               |DONE      |Manifest: NOSIGNATURE
		armorpointspp-1.16.5-2.0.0.jar                    |ArmorPoints++                 |armorpointspp                 |1.16.5-2.0.0        |DONE      |Manifest: NOSIGNATURE
		randomite-1.16.4-1.0.1.jar                        |Randomite Classic             |randomite                     |1.0.1               |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		expandedstorage-7.3.8+1.16.5.jar                  |Expanded Storage              |expandedstorage               |7.3.8               |DONE      |Manifest: NOSIGNATURE
		just_enough_keg-1.16.5-1.0.1.jar                  |Just Enough Keg               |just_enough_keg               |1.0.1               |DONE      |Manifest: NOSIGNATURE
		starterkit_1.16.5-3.1.jar                         |Starter Kit                   |starterkit                    |3.1                 |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.16-1.2.4.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.2.4               |DONE      |Manifest: NOSIGNATURE
		cherishedworlds-forge-1.16.5-5.1.1.0.jar          |Cherished Worlds              |cherishedworlds               |1.16.5-5.1.1.0      |DONE      |Manifest: NOSIGNATURE
		cryingportals_1.16.5-1.2.jar                      |Crying Portals                |cryingportals                 |1.2                 |DONE      |Manifest: NOSIGNATURE
		Craftable_NameTag 1.16.x.jar                      |Craftable Name Tag            |bkcraftablenametag            |[1.16,)             |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.13.49-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.13.49             |DONE      |Manifest: NOSIGNATURE
		Craftable-Golden-Apples-1.16.jar                  |Craftable Enchanted Golden App|muzuly_craftableenchantedgolde|1.0                 |DONE      |Manifest: NOSIGNATURE
		Babel-1.0.5.jar                                   |Babel                         |babel                         |1.0.5               |DONE      |Manifest: NOSIGNATURE
		JEPB-1.0.0.jar                                    |Just Enough Piglin Bartering  |jepb                          |1.0.0               |DONE      |Manifest: NOSIGNATURE
		TofuCraftReload-1.16.5-0.3.8.1.jar                |TofuCraftReload               |tofucraft                     |1.16.5-0.3.8.1      |DONE      |Manifest: NOSIGNATURE
		GameMenuModOption-1.16.4-1.8.2.jar                |Game Menu Mod Option          |gamemenumodoption             |1.8.2               |DONE      |Manifest: NOSIGNATURE
		wwta-1.16-2.0.jar                                 |When Was That Again           |wwta                          |1.16-2.0            |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v1.0.2-1.16.5-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |1.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		NekosEnchantedBooks-1.16-1.6.0.jar                |Neko’s Enchanted Books        |nebs                          |1.6.0               |DONE      |Manifest: NOSIGNATURE
		randombonemealflowers_1.16.5-1.4.jar              |Random Bone Meal Flowers      |randombonemealflowers         |1.4                 |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.16.5-1.5.13.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.13       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		BedBenefits-1.16.5-5.0.3.jar                      |BedBenefits                   |bedbenefits                   |5.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		JustEnoughAdvancements-1.16.5-1.0.2.jar           |Just Enough Advancements      |jea                           |1.16.5-1.0.2        |DONE      |Manifest: NOSIGNATURE
		jmi-1.16.5-0.4-23.jar                             |JourneyMap Integration        |jmi                           |1.16.5-0.4-23       |DONE      |Manifest: NOSIGNATURE
		potiondescriptions-1.16.5-1.5.3.jar               |Potion Descriptions           |potiondescriptions            |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		giantspawn_1.16.5-2.7.jar                         |Giant Spawn                   |giantspawn                    |2.7                 |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |DONE      |Manifest: NOSIGNATURE
		JustEnoughCalculation-1.16.5-3.8.6.jar            |Just Enough Calculation       |jecalculation                 |3.8.6               |DONE      |Manifest: NOSIGNATURE
		enchantingcommands_1.16.5-1.7.jar                 |Enchanting Commands           |enchantingcommands            |1.7                 |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.3.jar                       |Journeymap                    |journeymap                    |5.7.3               |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |DONE      |Manifest: NOSIGNATURE
		mcwifipnp-1.5.3-1.16.5-forge.jar                  |LAN World Plug-n-Play         |mcwifipnp                     |1.5.3               |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.16.5.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |DONE      |Manifest: NOSIGNATURE
		campfirespawnandtweaks_1.16.5-1.4.jar             |Campfire Spawn and Tweaks     |campfirespawnandtweaks        |1.4                 |DONE      |Manifest: NOSIGNATURE
		anvilrestoration_1.16.5-1.1.jar                   |Anvil Restoration             |anvilrestoration              |1.1                 |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.16.5-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.16.5-1.1.2-forge  |DONE      |Manifest: NOSIGNATURE
		deathquotes-2.0-1.16.5.jar                        |DeathQuotes                   |deathquotes                   |2.0-1.16.5          |DONE      |Manifest: NOSIGNATURE
		catalogue-1.5.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.5.0               |DONE      |Manifest: NOSIGNATURE
		fixedanvilrepaircost_1.16.5-1.6.jar               |Fixed Anvil Repair Cost       |fixedanvilrepaircost          |1.6                 |DONE      |Manifest: NOSIGNATURE
		recast_1.16.5-1.5.jar                             |Recast                        |recast                        |1.5                 |DONE      |Manifest: NOSIGNATURE
		extendedbonemeal_1.16.5-1.4.jar                   |Extended Bone Meal            |extendedbonemeal              |1.4                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		deathbackup_1.16.5-1.5.jar                        |Death Backup                  |deathbackup                   |1.5                 |DONE      |Manifest: NOSIGNATURE
		bouncierbeds_1.16.5-1.0.jar                       |Bouncier Beds                 |bouncierbeds                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.18.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.18              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		nohostilesaroundcampfire_1.16.5-3.8.jar           |No Hostiles Around Campfire   |nohostilesaroundcampfire      |3.8                 |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.4-10.jar                    |Titanium                      |titanium                      |3.2.8.4             |DONE      |Manifest: NOSIGNATURE
		Jade-1.16.4-2.8.1.jar                             |Jade                          |jade                          |2.8.1               |DONE      |Manifest: NOSIGNATURE
		inventorytotem_1.16.5-1.4.jar                     |Inventory Totem               |inventorytotem                |1.4                 |DONE      |Manifest: NOSIGNATURE
		Worldswithores.jar                                |Worlds with ores              |worlds_with_ores              |1.0.5               |DONE      |Manifest: NOSIGNATURE
		mooshroomspawn_1.16.5-1.4.jar                     |Mooshroom Spawn               |mooshroomspawn                |1.4                 |DONE      |Manifest: NOSIGNATURE
		inventorio-1.16-forge-1.6.1.jar                   |Inventorio                    |inventorio                    |1.6.1               |DONE      |Manifest: NOSIGNATURE
		difficultylock_1.16.5-1.3.jar                     |Difficulty Lock               |difficultylock                |1.3                 |DONE      |Manifest: NOSIGNATURE
		sushigocrafting-1.16.5-0.2.1.jar                  |Sushi Go Crafting             |sushigocrafting               |NONE                |DONE      |Manifest: NOSIGNATURE
		jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |DONE      |Manifest: NOSIGNATURE
		cyclepaintings_1.16.5-2.1.jar                     |Cycle Paintings               |cyclepaintings                |2.1                 |DONE      |Manifest: NOSIGNATURE
		JustEnoughProfessions-1.16.5-1.2.2.jar            |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |DONE      |Manifest: NOSIGNATURE
		JustEnoughCharacters-1.16.4-4.3.2.jar             |Just Enough Characters        |jecharacters                  |1.16.4-4.3.2        |DONE      |Manifest: NOSIGNATURE
		villagebellrecipe_1.16.5-1.2.jar                  |Village Bell Recipe           |villagebellrecipe             |1.2                 |DONE      |Manifest: NOSIGNATURE
		spawnegg-recipes.1.16-1.1.jar                     |SpawnEgg Recipes              |speggresp                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.4.1.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.1               |DONE      |Manifest: NOSIGNATURE
		IKnowWhatImDoing-3.2.0-forge.jar                  |I Know What I'm Doing         |iknowwhatimdoing              |3.2.0               |DONE      |Manifest: 42:2c:5e:4c:e2:f5:d1:07:7f:aa:29:ae:31:88:80:0c:b1:a6:87:6b:6a:2d:0f:67:57:e4:5a:4a:26:73:31:ac
		WorldHandler-1.16.5-2.12.6.jar                    |World Handler                 |worldhandler                  |1.16.5-2.12.6       |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |DONE      |Manifest: NOSIGNATURE
		extendedcreativeinventory_1.16.5-1.6.jar          |Extended Creative Inventory   |extendedcreativeinventory     |1.6                 |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v1.0.15-1.16.5-Forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		enhancedcelestials-2.0.9-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
		JustEnoughEffects-1.1.2.jar                       |Just Enough Effects           |effectinfo                    |1.1.2               |DONE      |Manifest: NOSIGNATURE
		Craftable Horse Armour  Saddle-1.16.5-1.7--Forge.j|CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.7                 |DONE      |Manifest: NOSIGNATURE
		CraftableTotemOfUndying-1.16.5-1.2.2.jar          |Craftable Totem Of Undying    |craftabletotemofundying       |1.2.2               |DONE      |Manifest: NOSIGNATURE
		inventorypause-mc1.16.5_v0.7.1.jar                |Inventory Pause               |inventorypause                |mc1.16.5_v0.7.1     |DONE      |Manifest: NOSIGNATURE
		healingcampfire_1.16.5-3.3.jar                    |Healing Campfire              |healingcampfire               |3.3                 |DONE      |Manifest: NOSIGNATURE
		drinkbeer-1.16.5-2.3.5.jar                        |Drink Beer                    |drinkbeer                     |2.3.5               |DONE      |Manifest: NOSIGNATURE
		aimassistance-1.4.0-MC1.16.x.jar                  |Aim Assistance                |aimassistancemod              |1.4.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 0acb6b77-fd8e-4d97-8a38-e8df9504f04b
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:secondchanceforge, mod:justenoughbeacons (incompatible), mod:zombiehorsespawn, mod:superflatworldnoslimes, mod:findme (incompatible), mod:villagerdeathmessages, mod:ctm (incompatible), mod:controlling, mod:bookshelf, mod:gilding, mod:cheat_mode (incompatible), mod:chancecubes (incompatible), mod:potionstacker, mod:jeed, mod:skeletonhorsespawn, mod:zombievillagersfromspawner, mod:jeresources, mod:peanutcraft, mod:ninjaphenix_container_lib (incompatible), mod:mineralchance, mod:anviltooltipmod, mod:betterspawnercontrol, mod:visiblearmorslots, mod:editsign, mod:edibles, mod:stumbleuponcamps, mod:fishontheline, mod:patchouli (incompatible), mod:basalt_walker, mod:armorpointspp, mod:randomite (incompatible), mod:collective, mod:expandedstorage (incompatible), mod:just_enough_keg, mod:starterkit, mod:inventoryprofilesnext (incompatible), mod:cherishedworlds, mod:cryingportals, mod:bkcraftablenametag, mod:cloth-config (incompatible), mod:muzuly_craftableenchantedgoldenapple, mod:babel, mod:jepb, mod:tofucraft, mod:gamemenumodoption, mod:wwta, mod:enchantinginfuser, mod:nebs, mod:randombonemealflowers, mod:cyclic (incompatible), mod:bedbenefits, mod:jea, mod:jmi, mod:potiondescriptions, mod:giantspawn, mod:jei, mod:jecalculation (incompatible), mod:enchantingcommands, mod:waystones (incompatible), mod:shutupexperimentalsettings (incompatible), mod:journeymap (incompatible), mod:naturescompass (incompatible), mod:mcwifipnp (incompatible), mod:configured, mod:libx, mod:campfirespawnandtweaks, mod:anvilrestoration, mod:explorerscompass, mod:deathquotes, mod:catalogue, mod:fixedanvilrepaircost, mod:recast, mod:extendedbonemeal, mod:forge, mod:deathbackup, mod:bouncierbeds, mod:enchdesc, mod:nohostilesaroundcampfire, mod:mousetweaks, mod:titanium (incompatible), mod:jade, mod:inventorytotem, mod:worlds_with_ores, mod:mooshroomspawn, mod:inventorio, mod:difficultylock, mod:sushigocrafting (incompatible), mod:jeiintegration, mod:cyclepaintings, mod:justenoughprofessions, mod:jecharacters (incompatible), mod:villagebellrecipe, mod:speggresp, mod:inventoryhud, mod:iknowwhatimdoing, mod:worldhandler (incompatible), mod:appleskin, mod:extendedcreativeinventory, mod:puzzleslib, mod:enhancedcelestials, mod:effectinfo, mod:craftablehorsearmour, mod:craftabletotemofundying, mod:inventorypause, mod:healingcampfire, mod:drinkbeer, mod:aimassistancemod (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by CorgiTaco** [comment]
delete your config files and let them regenerate.
