### ISSUE TITLE
[Bug]: 1.18.1 Client Crash with light textures

### ISSUE THREAD

**Issue by LunafeyLazuli** [CorgiTaco/Enhanced-Celestials#102]
### Mod Version

enhancedcelestials-2.0.9-1.18.jar

### Mod Loader

Forge

### Mod Loader Version

39.0.59

### What happened?

Sometimes crashes the client due to a weird light texture issue

### latest.log

https://gist.github.com/LunafeyLazuli/8488609f2f7ba654a5e1d61e664a4199

**Comment by KingPin** [comment]
getting this on 2.0.6 on fabric. same exact error as OP.

will post a log as soon as I can replicate it.

**Comment by CorgiTaco** [comment]
1.18.1 is no longer supported, if the issue persists please open a new issue
