### ISSUE TITLE
[Bug]: Crashing at starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [CorgiTaco/Enhanced-Celestials#104]
### Mod Version

2.0.6

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

Is crashing at starting.

### latest.log

https://bytebin.lucko.me/UBNgQylSI7

**Comment by Prodicalx** [comment]
I have this same issue
No idea how to fix it

**Comment by CorgiTaco** [comment]
Please use the latest files for enhanced celestials on curseforge, 1.18.1 files DO NOT work with 1.18.2
