### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MystiaTech** [CorgiTaco/Enhanced-Celestials#105]
### Mod Version

2.0.9

### Mod Loader

Forge

### Mod Loader Version

36.2.29

### What happened?

We are attempting to use Magma instead of the regular forge launcher to allow us to use plugins with our server.

### latest.log

https://gist.github.com/Advtech92/16db52d0aace70b55e9ebb8d662e00e4

**Comment by CorgiTaco** [comment]
Plugin launchers are not supported, please use the forge launcher
