### ISSUE TITLE
[Bug]:  1.18.2 support

### ISSUE THREAD

**Issue by zachsai** [CorgiTaco/Enhanced-Celestials#106]
### Mod Version

2.0.9

### Mod Loader

Forge

### Mod Loader Version

4.0.17

### What happened?

Please add 1.18.2 support since most mods are pushing for this patch. 1.18.1 is not forward compatible

### latest.log

[https://pastebin.com/1WYegaJk](https://pastebin.com/1WYegaJk)

**Comment by Sunconure11** [comment]
https://gist.github.com/Sunconure11/027ed0f2373b84514f7b16c7b896b86f

Can confirm the same with Fabric. @CorgiTaco

**Comment by KakashoLin** [comment]
Can you update to 1.18.2? This is a mod that was used by major modpacks and is missing in 1.18.2 editions.

**Comment by CorgiTaco** [comment]
done, see curseforge page
