### ISSUE TITLE
Config for blood moon and super blood moon

### ISSUE THREAD

**Issue by AdrianRB9** [CorgiTaco/Enhanced-Celestials#107]
### Mod Version

1.16.5

### Mod Loader

Forge

### Mod Loader Version

enhancedcelestials-2.0.9-1.16.5

### What happened?

How can I configure the mod so that every night is a blood moon and a super blood moon? 

### latest.log

.

**Comment by CorgiTaco** [comment]
in the `lunar-settings.json` config file set `  "minDaysBetweenLunarEvents"` to 1 and in the respective config file for the moon event set `  "minNumberOfNightsBetween"` to 1
