### ISSUE TITLE
Incorrect path for config files

### ISSUE THREAD

**Issue by iCeParadox64** [CorgiTaco/Enhanced-Celestials#110]
(1.18.2 Forge) 

According to you in the Discord, the intended path for the config files is `config\enhancedcelestials\modid\dimensionname\lunar`. However, they're actually being created in `config\minecraft\dimensionname\lunar`.

**Comment by Maypul** [comment]
Can confirm, also 1.18.2, Forge 40.1, mod version 2.0.6.

Checking 1.16.5 version, there seem to be enhancedcelestials-common.toml file along modname folders (so in this case minecraft's) but in 1.18 I can't find it, even with in-game config editor it shows that EC has no config file.

**Comment by CorgiTaco** [comment]
Fixed in https://github.com/CorgiTaco/Enhanced-Celestials/commit/12231c335c456179b8c5033bf83102ce83484931
