### ISSUE TITLE
[Bug]: Sleeping not completely prevented during blood moon

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/Enhanced-Celestials#129]
### Minecraft Version

1.18.2

### Enhanced Celestials Version

2.0.7

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### Bug Severity

Minor

### What happened?

When attempting to sleep during a blood moon, you will appear to hop into the bed then be kicked out.  
It should display a message such as "You may not rest now; there is a blood moon" without allowing the player to enter the bed.

### latest.log

N/A

**Comment by CorgiTaco** [comment]
This is intentional as it's more widely compatible in preventing entities beyond the player from sleeping as it's checked inside of tick

**Comment by MarioSMB** [comment]
That's a shame, as it's a very strange behaviour - it sounds like Forge itself needs to make better API support for cancelling sleep.
