### ISSUE TITLE
[Bug]: Unable to Locate Config file in 1.19.2 version of Mod

### ISSUE THREAD

**Issue by Karvoo** [CorgiTaco/Enhanced-Celestials#131]
### Minecraft Version

1.18.2

### Enhanced Celestials Version

Enhanced_Celestials-fabric-1.19-2.1.0.1

### Mod Loader

Fabric

### Mod Loader Version

fabric 1.19.2

### Bug Severity

Minor

### What happened?

*** Note: unable to select correct version of minecraft from your bug report dropdown menu

I have experience using this on a 1.19 fabric server && have configured the configs easily. However, in using the 1.19.2 version on my newer 1.19.2 server, the mod works just fine but I can not locate the server configs for it. I have literally searched every single folder on the FTP access of my server; nothing lunar or enhanced or celestial could be located even using the search function on Filezilla. The file doesn't seem to be generating on the client side either. I've removed the mod && re-added it to see if a sort of "fresh install/reboot" would generate the file, but still nothing.

Has it been renamed something vastly different && that is why I am unable to find it?

*****The log file is a blank text file since it doesn't apply to my issue && I am unable to submit without putting something there**

### latest.log

[Not Applicable.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/9531040/Not.Applicable.txt)

**Comment by CorgiTaco** [comment]
Configs were moved to datapacks: https://github.com/CorgiTaco/Enhanced-Celestials/wiki

Sorta like world gen datapacks
