### ISSUE TITLE
Crash report with Enhanced Celestials 1.0.1 MCV: 1.16.4/1.16.5 with 177 mods

### ISSUE THREAD

**Issue by DoctorArchives** [CorgiTaco/Enhanced-Celestials#14]
Every time I add this mod in my personal modpack, I get this crash although it might be a mod that is interfering.

Fair warning, I haven't tried this mod without all these mods.
Here's the crash:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/16/21 2:19 AM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.20)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.render.GameRenderer.<init>(GameRenderer:159)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:533)
	at net.minecraft.client.main.Main.main(Main:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_765::method_3313(F)V has incompatible changes at opcode 183 in callback net/minecraft/class_765::doOurLightMap.
Expected: [Lnet/minecraft/class_638;, F, F, F, Lnet/minecraft/class_1160;]
   Found: [Lnet/minecraft/class_638;, F, F, F, F]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5836846016 bytes (5566 MB) / 8321499136 bytes (7936 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Suspected Mods: Fabric Loader (fabricloader)
	Fabric Mods: 
		adabraniummod: Adabranium 1.3.2+1.16.5
		adapaxels: AdaPaxels 1.0.6+1.16.5
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.2
		advancednbttooltip: Advanced NBT Tooltips 1.3.0+build.2-1.16.4
		adventure-platform-fabric: adventure-platform-fabric 4.0.0-SNAPSHOT
		alaskanativecraft: Alaska Native Craft 1.0.2
		amecs: Amecs 1.3.3+mc.1.16.3
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		architectury: Architectury 1.6.114
		artifacts: Artifacts 2.3.0+fabric
		artifice: Artifice 0.13.1+1.16.2-rc1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		beaconoverhaul: Beacon Overhaul 1.2.0+1.16
		beaconsforall: Beacons For All 1.4.1-1.16.5
		bedspreads: Bedspreads 1.3.1-1.16.4
		beenfo: Beenfo 1.16.5-fabric0.30.0-1.3
		betterf3: BetterF3 1.1.2
		biomepicker: Biome Picker 1.1
		blue_endless_jankson: jankson 1.2.0
		camp_fires_cook_mobs: Camp Fires Cook Mobs 1.1.7+MC1.16.2-1.16.5
		campanion: Campanion 1.3.2
		cardinal-components: Cardinal Components API 2.7.10
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		carrier: Carrier 1.7.4
		cavebiomes: Cave Biomes 0.6.2
		cdsam: Survival Additions 1.3.2-Fabric-1.16.5
		chainmail: Chainmail 0.5.0
		chat_heads: Chat Heads 0.2.2+1.16.2
		chorus_links: Chorus Links 1.2.1
		cinderscapes: Cinderscapes 1.3.3
		cleanview: CleanView 1.16.5-v1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		colorfulcolumns: Colorful Columns 1.0.0
		columns: Columns 1.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cosmetic-armor: Cosmetic Armor 1.0.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		cpas: conveniently placed armor slots 1.3.0+1.16.5
		craftingpad: Crafting Pad 1.16.5-fabric0.30.0-1.0.5
		croptosis: Croptosis 1.0.1
		crowdin-translate: CrowdinTranslate 1.2
		cullleaves: Cull Leaves 2.0.0
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.11-1.16.4
		curiousshulkerboxes: Curious Shulker Boxes 1.1.1-1.16.5
		customsplashscreen: Custom Splash Screen 1.0.0
		decorative: Decorative 4.0.0
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dracomelette: Dracomelette 1.16.5-1
		dropz: Dropz 1.0.2
		dt: Damage Threshold 1.3
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		dynmus: Dynamic Music 1.0.0
		earthtojavamobs: Earth2Java 1.6.1+1.16.4
		economical_villager_trading: Economical Villager Trading 1.0.3+MC1.16.4-1.16.5
		editsign: Edit Sign 2.2.0
		eggtab: Egg Tab 2.1.0+1.16-fabric
		eldritch_mobs: Eldritch Mobs 1.6.8
		elhuevo: El Huevo 1.16.5-1.0.0
		emerald_tools: Emerald Tools 1.1.1
		enchant_giver: Enchant Giver 1.0.2
		enchantment_lore: EnchantmentLore 1.1.1+MC1.16.1-1.16.5
		enhancedcelestials: Enhanced Celestials 1.0.1
		enhancement: Enhancement (Fabric) 0.4.0
		environmentz: EnvironmentZ 1.0.9
		expandedstorage: ExpandedStorage 5.6.32
		expcontainer: Experience Container [XP] 1.12
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabrication: Fabrication 1.3.1
		fabricloader: Fabric Loader 0.11.1
		fabrictailor: Fabric Tailor 1.4.0-1.16.4
		fading: Fading 1.1.0
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		faster-minecarts: Faster Minecarts 1.1.2
		fedora: Fedora 1.1.1-fabric-1.16.4
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.20
		gizmos: Gizmos 1.2.1
		goldenhoppers: Golden Hoppers 1.0.1
		goldensteak: Goldensteak 1.0.2
		greater_eye: Greater Eye of Ender 1.1.5
		harvest_scythes: Harvest Scythes 1.0.9
		headsdowndisplay: Heads down display 0.0.0
		heartbond: Heartbond 1.0.0
		hitmarker: HitMarker 1.0a-1.16.2
		homecamp: Home Camp 1.0.3
		hplus: Hopper Plus 1.0.10
		improved-stations: Improved Stations 2.0.3
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lapisreserve: Lapis Reserve 1.0.6
		launchersmod: Launchers 3.2.0
		lchunkloader: Literally Chunk Loader 1.3.5
		lengthyladders: Lengthy Ladders 1.0.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		maelstrom_library: Maelstrom Library 1.0-1.16.5
		magic_lanterns: Magic Lanterns 1.1.0
		map_atlases: Map Atlases 1.0.0
		mcda: MC Dungeons Armors 0.9.4
		mcdw: MC Dungeons Weapons 2.6.1
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		minegate-moreblocks: MineGate - MoreBlocks 1.1.1
		missingnetherblocks: Missing Nether Blocks 2.0.1
		mm: Manningham Mills 2.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.2-1.16.5
		modmenu: Mod Menu 1.16.7
		monster-in-the-closet: Monsters in the Closet 1.0.0
		moreberries: More Berries 1.3.4
		moreblocksmod: More Blocks Mod 0.1.4
		morefences: More fences and walls 1.16.5
		morepaintings: More Paintings 1.0.4
		morerespawnanchors: More Respawn Anchors 1.0.1
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		multi_item_lib: Multi Item Lib 1.1.1
		nbexpand: Noteblock Expansion 1.1.1
		net_kyori_adventure-api: adventure-api 4.4.0
		net_kyori_adventure-key: adventure-key 4.4.0
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.4.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.4.0
		net_kyori_examination-api: examination-api 1.0.0
		net_kyori_examination-string: examination-string 1.0.0
		net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11
		netherite_nugget: Netherite Nugget 1.2.1
		netherite_plus: Netherite Plus Mod 1.3.17-1.16.5
		nha: Netherite Horse Armor 1.1.0
		notchify: Notchify 0.4.0-configmenu.1
		notenoughanimations: NotEnoughAnimations 1.1.0
		notenoughcrashes: Not Enough Crashes 3.1.5
		nourish: Nourish 1.2.1
		noweakattack: No Weak Attack 1.1.0
		operate: Operate 1.1.3
		opitems: Op Items 1.0.0
		optifabric: OptiFabric 1.9.2
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		oro_config: OroArmor Config 1.2.0
		overpowered_mending: Overpowered Mending 2.2.3
		paintingcycle: Painting Cycle 1.0.0
		phantompillows: Phantom Pillows 1.1.0
		placeholder-api: Fabric Placeholder API 0.2.0
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		powershot: Powershot 1.1.1-1.16.2-fabric
		prehistoric: Prehistoric 1.0.0
		pulverizer_mod: Pulverizer Mod 1.1.1
		quartzelv: Quartz Elevator 1.1.0
		quickshulker: Quick Shulker 1.1.12-1.16
		randomblockplacement: RandomBlockPlacement 1.16.5-fabric0.30.0-1.1.1
		rare-ice: Rare Ice 0.2.2
		rayon: Rayon 1.0.9
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		redbits: Red Bits 1.7.0
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		reroll: Reroll 1.2.0-1.16.5
		respawnablepets: Respawnable Pets 1.16.5-1
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.9.1
		roughlyenoughitems-api: REI (API) 5.9.1
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.9.1
		roughlyenoughitems-runtime: REI (Runtime) 5.9.1
		rpgstats: RPGStats 3.1.0+1.16.4
		ruined_equipment: Ruined Equipment 1.2.3
		seamless_loading_screen: Seamless Loading Screen 1.1.0
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		shulkercharm: Shulker Charm 1.1.2+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		simple_backpack: SimpleBackpack 1.0.38
		simplemeasuring: Simple Measuring 1.0.0
		skinnedlanterns: Skinned Lanterns 1.16.5-1.1.3
		slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
		slime_sling: SlimeSling 1.0.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		spawnerminecartitem: Spawner Minecart Item 1.0.0
		spellbound: Spellbound 1.1.3
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		sturdygold: sturdy gold 0.1.0
		suitablystackablestew: Suitably Stackable Stew 1.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		throwabletorch: Projectile Tutorial Mod 1.0.0
		timechanger: Time Changer 1.0.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		tooltipfix: ToolTip Fix 1.0.2-1.16
		totemmod: Wither Totems Mod 0.3.2
		transliterationlib: TRansliterationLib 1.0.2
		traverse: Traverse 3.3.1
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.3
		ttc: Tiny Trash Can 1.2.0
		unearthed: Unearthed 1.1.0
		vafoen: Vanilla Food Enhanced 1.1.1
		vehiclefix: VehicleFix 1.0
		verticalredstone: Vertical Redstone 1.2.0
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		wandering_collector: Wandering Collector 1.0.0+mc1.16.5
		wildworld: Wild World 2.0.0+1.16.5
		worldedit: WorldEdit 7.2.2+fc3c499
		worldeditcui: WorldEditCUI 1.16.5+02
		wtoas: Wandering Trader on a Stick 1.1.0
		xaerobetterpvp: Better PVP Mod 21.1.1
		xaeroworldmap: Xaero's World Map 1.11.10
		xp_storage: XP Storage 1.4+1.16.5
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.40, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre2.zip
	OpenGlVersion: 4.6.0 NVIDIA 461.40
	OpenGlRenderer: GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\shafe\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G6\Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by coolsimulations** [comment]
You do realise that this is a _Minecraft Forge_ mod, not a _Fabric_ mod? Looks like your running Fabric.

**Comment by CorgiTaco** [comment]
Fixed by optifabric
