### ISSUE TITLE
[Bug]: No way to modify default events

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/Enhanced-Celestials#149]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

2.1.0.2

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

There does not appear to be data files for the default lunar events making it difficult or impossible to modify them.

### latest.log

N/A

**Comment by CorgiTaco** [comment]
Use the `/corgilib worldRegistryExport` command to generate the datapack for your current world, you'll edit the files for the lunar events and add those files to the world's datapack folder. See the [wiki](https://github.com/CorgiTaco/Enhanced-Celestials/wiki) for more details.

Latest versions can be found here: 
Forge: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/4392661 / https://modrinth.com/mod/enhanced-celestials/version/1.19.2-2.1.0.4-forge
Fabric: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/4392659 / https://modrinth.com/mod/enhanced-celestials/version/1.19.2-2.1.0.4-fabric

**Comment by MarioSMB** [comment]
Glad to see the wiki is working now. With that said, I see no mention there of that command - maybe something to address within the "adding and editing" page of lunar events?  

Additionally, I do think it would be wise to include the default datapack files with the mod's .jar file so that they can be easily modified, but that's just my opinion!

**Comment by CorgiTaco** [comment]
Added the command to wiki, ty for pointing that out.
