### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Timkokain** [CorgiTaco/Enhanced-Celestials#150]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

2.1.0.2

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

The following message is displayed when the server starts.
```txt
[modloading-worker-0/ERROR] [minecraft/Util]: Registry 'enhancedcelestials:lunar/event' was empty after loading

[modloading-worker-0/ERROR] [minecraft/Util]: Registry 'enhancedcelestials:lunar/dimension_settings' was empty after loading
```
Not sure if that's how it should be. So I decided to let you know.

### latest.log

[_minecraft-java_logs.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/10366107/_minecraft-java_logs.txt)

**Comment by CorgiTaco** [comment]
Non issue, just MC warning about it bc i register the events in forge events
