### ISSUE TITLE
[Crash]: 1.20.1 When creating World

### ISSUE THREAD

**Issue by xd4rkzghost01** [CorgiTaco/Enhanced-Celestials#161]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

Enhanced_Celestials-forge-1.20.1-5.0.0.1

### Mod Loader

Forge

### Mod Loader Version

47.0.14

### What happened?

Hi ! I lunch the game. Everthing fine, and the when i hit the Singleplayer button for the 1st time, it crash the game 0.5 sec after it.
I know there was a issue like this #160 , but for my defense, i dont have Geode install and (only) 65 mod installed. Also, having Oculus install (since Optifine cause a lot of issue with other mods).

### crash-log

[crash-2023-06-21_15.56.16-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/11826080/crash-2023-06-21_15.56.16-client.txt)

### latest.log

[2023-06-21-7.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/11826083/2023-06-21-7.log)

**Comment by CorgiTaco** [comment]
Thank you for the report! I will check this out soon!
