### ISSUE TITLE
Flickering lighting color every moment or so.

### ISSUE THREAD

**Issue by Corvus20** [CorgiTaco/Enhanced-Celestials#17]
In the middle of the day, a random flicker of the blood moon or harvest moon lighting will occur every few seconds or so. I am unsure of what can be going wrong, as the logs/console feed show no signs of anything going wrong. Is this a known issue?

**Comment by CorgiTaco** [comment]
Should be fixed here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430183

Reopen this report if the issue persists
