### ISSUE TITLE
[Crash]: 1.20.1 Incompatible with recent Fabric Api versions

### ISSUE THREAD

**Issue by kingkuys2123** [CorgiTaco/Enhanced-Celestials#171]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.14.22

### What happened?

The game crashed upon loading world and sometimes on startup, showing `Missing registry: ResourceKey[minecraft:root / enhancedcelestials:lunar/dimension_settings`  in the crash logs.

They also experienced the same crash by using the EC mod with the recent Fabric Api versions in 1.20.1
https://github.com/CorgiTaco/Enhanced-Celestials/issues/165#issuecomment-1641403631
https://github.com/CorgiTaco/Enhanced-Celestials/issues/165#issuecomment-1642675121
https://github.com/CorgiTaco/Enhanced-Celestials/issues/165#issuecomment-1647850634

### crash-log

https://pastebin.com/MHbvJ9ut

### latest.log

https://pastebin.com/pvkh5Rqy

**Comment by MayandJohnny** [comment]
Yea I am having the same issue. Because of this optifine/optifabric won't run correctly.

**Comment by CorgiTaco** [comment]
Fixed for versions 5.0.0.3 and beyond!
