### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jack22891** [CorgiTaco/Enhanced-Celestials#173]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

5.0.0.2

### Mod Loader

Forge

### Mod Loader Version

47.1.44

### Bug Severity

Major

### What happened?

Incompatibility issue with optifine. I've isolated every mod in my pack, and the game will only crash when optifine is with this mod. Any fix or workaround?

### latest.log

[crash-2023-08-22_10.06.50-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12410225/crash-2023-08-22_10.06.50-client.txt)

**Comment by CorgiTaco** [comment]
Yup this mod is incompatible with optifine! Please use an alternative mod!!
