### ISSUE TITLE
[Crash]: crash on startup

### ISSUE THREAD

**Issue by btd6fdds** [CorgiTaco/Enhanced-Celestials#176]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

5.0.0.2

### Mod Loader

Forge

### Mod Loader Version

Forge 47.1.0

### What happened?

I launch MC and it does the normal forge mod loading then crashes.

### crash-log

[crash-2023-08-29_02.07.16-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12459247/crash-2023-08-29_02.07.16-client.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/12459249/latest.log)

**Comment by btd6fdds** [comment]
should note that I am on 1.20.1 and using the most recent version of the mod

**Comment by Zeyeo** [comment]
Hello, I am also experiencing this issue with "Enhanced_Celestials-forge-1.20.1-5.0.0.2"
Forge - 47.1.43

here is the log.

[crash-2023-09-06_22.17.11-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12543955/crash-2023-09-06_22.17.11-client.txt)

**Comment by rcxwhiz** [comment]
I was also recently having a crash on load. I didn't have CorgiLib. When I loaded with other mods, this just resulted in a non-descriptive crash, but when I loaded enhanced celestials by itself it was able to tell me that it was missing that library.

**Comment by CorgiTaco** [comment]
Optifine is incompatible with this mod. Please use an alternative mod for shaders
