### ISSUE TITLE
[Bug]: Harvest moon better crop harvest does not work at all on Fabric 1.20.1

### ISSUE THREAD

**Issue by FrozenDragon0** [CorgiTaco/Enhanced-Celestials#180]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

1.20.1-5.0.0.2

### Mod Loader

Fabric

### Mod Loader Version

Fabric 0.14.21

### Bug Severity

Major

### What happened?

During a Harvest moon crops are meant to be multiplied when broken, however for whatever reason this does not work at all on Fabric 1.20.1 effectively making the Harvest moons useless.

Strangely enough however the forge version of the mod on the same game version does not have this issue, seems to be merely a Fabric problem.

3 Fully grown wheat crops broken and all 3 only dropped 1 wheat when I should've received double due to it being a Harvest Moon.
![2023-09-28_11 14 00](https://github.com/CorgiTaco/Enhanced-Celestials/assets/18079316/bab7ff58-39d8-47f4-8e3f-08547cb87cf4)

### latest.log

[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/12745160/latest.log)

**Comment by CorgiTaco** [comment]
Fixed in 5.0.0.4
