### ISSUE TITLE
[Crash]: incompatible/incorrect files possibly caused by optifine on 1.19.4

### ISSUE THREAD

**Issue by toxicblonde** [CorgiTaco/Enhanced-Celestials#181]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

4.0.0.1

### Mod Loader

Forge

### Mod Loader Version

45.0.23

### What happened?

Apologies, I have never had this type of crash before and I apologize if this type of error is not of the modder's concern. Game is unable to render due to a sponge/mixin error?. Under the crash report I can pick out this line:

> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/client/renderer/LightTexture::m_109881_(F)V has incompatible changes at opcode 87 in callback enhancedcelestials.mixins.json:client.MixinLightMapTexture->@Inject::doOurLightMap(FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/client/multiplayer/ClientLevel;FFFFFFFLorg/joml/Vector3f;)V.
 Expected: [Lnet/minecraft/client/multiplayer/ClientLevel;, F, F, F, F, F, F, F, Lorg/joml/Vector3f;]
    Found: [Lnet/minecraft/client/multiplayer/ClientLevel;, Z, F, F, F]
Available: [Lnet/minecraft/client/multiplayer/ClientLevel;, Z, F, F, F]

I've troubleshooted the last couple days and as far as I can tell, it is a problem in part from Optifine HD_U_I3. I know CorgiTaco is not responsible for Optifine's problems but I only come across this problem from Enhanced Celestials. Is this an issue I can correct on my end (config and the like) or is this irremediable for me as the user? I have tested my entire 'modpack' now with Rubidium and no issues whatsoever so I'm stumped :(

### crash-log

[crash-2023-10-07_19.30.54-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12839523/crash-2023-10-07_19.30.54-client.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/12839538/latest.log)

**Comment by MatthewGimbut** [comment]
I've hit this problem as well. Were you able to find any way to work around it, or is the only option to disable one of the two mods?

**Comment by toxicblonde** [comment]
> I've hit this problem as well. Were you able to find any way to work around it, or is the only option to disable one of the two mods?

sorry, I started school and a new job so I abandoned it completely due to no workaround, if I recall correctly. & yes, only option was to disable one or the other.

**Comment by MatthewGimbut** [comment]
> > I've hit this problem as well. Were you able to find any way to work around it, or is the only option to disable one of the two mods?
> 
> sorry, I started school and a new job so I abandoned it completely due to no workaround, if I recall correctly. & yes, only option was to disable one or the other.

Ah no problem. It's not much of a fix but I was able to work around the issue by using embeddium+oculus to load shaders instead of optifine, if you or anyone else in the future sees this and needs a workaround

**Comment by CorgiTaco** [comment]
Yeah optifine is incompatible. They do far too many hacks and other things that just make it impossible to work with
