### ISSUE TITLE
[Crash]: Setting moon event to "default" crashes and continues to crash world

### ISSUE THREAD

**Issue by Darkmega18** [CorgiTaco/Enhanced-Celestials#182]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

Enhanced_Celestials-forge-1.19.2-2.1.0.6.jar

### Mod Loader

Forge

### Mod Loader Version

forge-43.3.2

### What happened?

I was testing the difference of surface mobs between normal darkness, blood moon and super blood moon for a friend who was curious (and scared cause he just got a super blood moon when coming back from afk).

Being silly, I set the moon event to "default" thinking that was standard moon mode where nothing was happening. But instead it crashed my game and after trying to go back in, it keeps happening. Something about a missing resource key.

### crash-log

[crash-2023-10-12_05.35.16-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12873619/crash-2023-10-12_05.35.16-server.txt)
[crash-2023-10-12_05.31.25-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/12873620/crash-2023-10-12_05.31.25-server.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/12873622/latest.log)

**Comment by Polkadoty** [comment]
I started getting this bug on fabric as well. Exactly the same with the missing resource key.

**Comment by dinkley** [comment]
Has this not been fixed yet? Still happens as of Fabric 1.20.1 5.0.0.2. Why is `enhancedcelestials:default` an option if the mod crashes as soon as it gets set?

A temporary solution is to go into the /world/data directory and delete the enhanced celestials data file.

**Comment by CorgiTaco** [comment]
I want to say this is fixed on 5.0.0.3. If its not please reopen this issue/make a new one.

**Comment by WarrLord47** [comment]
Just got this on Forge 1.20.1 with mod version 5.0.1.0. Disabling the mod lets me access the world after, but with the mod enabled always crashes me to desktop if I try to reset the moon to normal.
