### ISSUE TITLE
[Bug]: 1.20 version configs need to be done via datapack

### ISSUE THREAD

**Issue by Talidorn** [CorgiTaco/Enhanced-Celestials#185]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar

### Mod Loader

Forge

### Mod Loader Version

47.1.3

### Bug Severity

Minor

### What happened?

You've moved from config files to datapacks.

As a server owner, that has no experience with datapacks, this has made changing how your mod operates untenable.

Please document how to make changes to the datapack or add commands that will allow me to change how the features work. If my server has 10+ people on and a blood moon happens the night will last 20-25 minutes in real time vs. 7-10 for other nights. This is due to the excessive mob count the blood moon generates.

Please consider adding commands to help me make changes to the config so I don't have to learn how to change via datapacks. I'd hate to eliminate your mod from my server due to my lack of understanding on the datapack configuration method.

Thanks!

### latest.log

none

**Comment by Talidorn** [comment]
PS - as you have 1.20 versions please allow tickets to choose 1.20.

**Comment by ahbaker** [comment]
I also would prefer a config file. /corgiLib does not let me obtain the datapack/

Thanks

**Comment by seriousfreezing** [comment]
Datapack is trash!

**Comment by zeid0ne** [comment]
I also rather config files

**Comment by Luktasclip** [comment]
me too... 1.20.5 and they still dont fix it

**Comment by CorgiTaco** [comment]
[Wiki](https://github.com/CorgiTaco/Enhanced-Celestials/wiki) explains in depth how to set up and use enhanced celestial data packs.


 I've chosen to use datapacks for 2 reasons:

1. Mojang has gone down this road of datapacks.
2. The ability for other mod/datapack devs to upload their own "Lunar Event Packs" to curseforge and modrinth.

One cannot upload "config packs" to curseforge or modrinth.

**Comment by CorgiTaco** [comment]
> I also would prefer a config file. /corgiLib does not let me obtain the datapack/
> 
> Thanks

Wiki explains how to extract the datapack files from the mod jar
