### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by benio1394** [CorgiTaco/Enhanced-Celestials#187]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

5.0.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.15.1

### What happened?

Game crash when world is created

### crash-log

https://pastebin.com/BiaquTjS

### latest.log

https://pastebin.com/3UMELgm5

**Comment by benio1394** [comment]
Sorry that I put 1.19.2 version, but I have no option to choose 1.20.1

**Comment by LyonGalaxy** [comment]
I'm having the exact same crash! No matter what version of Enhanced Celestials i'm using

**Comment by CorgiTaco** [comment]
Fixed for versions 5.0.0.3 and beyond!
