### ISSUE TITLE
[Suggestion][Wiki] Provide examples of datapacks

### ISSUE THREAD

**Issue by FernandoCalaza** [CorgiTaco/Enhanced-Celestials#188]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

Doesn’t Matter

### Mod Loader

Forge

### Mod Loader Version

Doesn’t matter

### Bug Severity

Minor

### What happened?

    An example of a configuration datapack (default or customized) could be made available for download, along with information on how to configure it, on the wiki.

    I'm new to MC modding and I had no idea how to make a datapack. I spent 3x as much time trying to create one instead of configuring and customizing it. I saw that other players go through similar things, or even stop using the mod, because they believe the configuration process is complex.

    I truly believe that a downloadable example would help the community, so much so that I made my results available (https://www.planetminecraft.com/data-pack/enhanced-celestial-config/). But I know that people rarely get to my datapack when they are configuring the mod for the first time.

    So I ask again to make an example datapack available on the wiki.

### latest.log

Doesn’t Matter

**Comment by Aceplante** [comment]
https://github.com/CorgiTaco/Enhanced-Celestials/tree/f698f1c811fb9d4e931c47dec802f3b9b8347f48/Fabric/src/generated/resources/data/enhancedcelestials/lunar/event

**Comment by FernandoCalaza** [comment]
Thanks
