### ISSUE TITLE
[Bug]: /corgilib worldRegistryExport does nothing

### ISSUE THREAD

**Issue by SireOfTheQuags** [CorgiTaco/Enhanced-Celestials#189]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

5.0.0.2

### Mod Loader

Forge

### Mod Loader Version

47.1.84

### Bug Severity

Major

### What happened?

Command to get the datapack ''/corgilib worldRegistryExport'' does absolutely nothing. I have Corgilib installed.

### latest.log
[2023-12-21-7.log.gz](https://github.com/CorgiTaco/Enhanced-Celestials/files/13744702/2023-12-21-7.log.gz)

**Comment by Bobster3d** [comment]
This command was removed from Corgilib a while ago, but the information on this mod has not been updated to reflect that.

As someone else who is wanting to edit my configs I would like a solution too

**Comment by Aceplante** [comment]
same

**Comment by CorgiTaco** [comment]
The alternative for this now is to open up the mod jar file and pull the datapack sitting inside of the `data` folder. Wiki should reflect this now. Here: https://github.com/CorgiTaco/Enhanced-Celestials/wiki/1.19---Adding,-Deleting,-or-Editing-Lunar-Events-(Start-Here!)
