### ISSUE TITLE
Crashes with the origins mod

### ISSUE THREAD

**Issue by BlazingBen10** [CorgiTaco/Enhanced-Celestials#19]
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

![image](https://user-images.githubusercontent.com/79714522/109330562-73375180-7864-11eb-9312-24b3a25a33e4.png)

**Comment by CannibalKon** [comment]
It's likely an issue with Optifine, I am running every other mod on that list (plus 200 more) aside from the two optifine mods and wthit.

**Comment by CorgiTaco** [comment]
> 
> 
> It's likely an issue with Optifine, I am running every other mod on that list (plus 200 more) aside from the two optifine mods and wthit.

It most defintely isnt

**Comment by CorgiTaco** [comment]
fixed by optifabric
