### ISSUE TITLE
Create map crash[Crash]: 

### ISSUE THREAD

**Issue by zc1108aaa** [CorgiTaco/Enhanced-Celestials#194]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

-fabric-1.20.1-5.0.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.15.4

### What happened?

Create map crash[Crash]: 

### crash-log

[crash-2024-01-17_14.35.43-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/13959653/crash-2024-01-17_14.35.43-client.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/13959656/latest.log)

**Comment by CorgiTaco** [comment]
Fixed for versions 5.0.0.3 and beyond!
