### ISSUE TITLE
[Crash]: java.lang.NullPointerException: Cannot invoke "corgitaco.enhancedcelestials.api.lunarevent.LunarEvent.getClient()" because "lastEvent" is null

### ISSUE THREAD

**Issue by Vcool122** [CorgiTaco/Enhanced-Celestials#195]
### Minecraft Version

1.18.2

### Enhanced Celestials Version

2.0.7

### Mod Loader

Forge

### Mod Loader Version

40.2.17

### What happened?

I was fighting some mobs and I guess as soon as a lunar event spawned it crashed.

### crash-log

https://bytebin.lucko.me/HbdKY6GY4s

### latest.log

[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/14348830/latest.log)

**Comment by CorgiTaco** [comment]
Due to the lack of time I will no longer be supporting versions of this mod that are 1.20 and lower. Apologies for the inconvenience.
