### ISSUE TITLE
[Bug]: 1.19数据包配置无效.求配置文件

### ISSUE THREAD

**Issue by sxhmmmmm** [CorgiTaco/Enhanced-Celestials#196]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

1.0.0.34

### Mod Loader

Forge

### Mod Loader Version

43.3.8

### Bug Severity

Major

### What happened?

数据包配置无效

### latest.log

数据包配置无效

**Comment by CorgiTaco** [comment]
Please make an issue report in english
