### ISSUE TITLE
[Crash]: On creating a new world 1.20.1 Fabric

### ISSUE THREAD

**Issue by DTX3** [CorgiTaco/Enhanced-Celestials#197]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

1.20.1-5.0.0.2

### Mod Loader

Fabric

### Mod Loader Version

Fabric 0.92.0 1.20.1

### What happened?

Minecraft version 1.20.1

Upon creating a new world the game crashes with the following error: 

java.lang.RuntimeException: Mixin tThe game crashed whilst exception in server tick loop
Error: java.lang.IllegalStateException: Missing registry: ResourceKey[minecraft:root / enhancedcelestials:lunar/dimension_settings]

### crash-log

[crash-2024-03-27_23.18.33-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/14782151/crash-2024-03-27_23.18.33-server.txt)

### latest.log

[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/14782157/latest.log)

**Comment by HeavyLogic** [comment]
Same here. https://pastebin.com/XHtgBD0X

**Comment by CorgiTaco** [comment]
Fixed for versions 5.0.0.3 and beyond!

**Comment by DTX3** [comment]
> Fixed for versions 5.0.0.3 and beyond!

Thank you! It now works a treat ;)
