### ISSUE TITLE
[Crash]: Mixin Incompatibility with Botania

### ISSUE THREAD

**Issue by LeakingAmps** [CorgiTaco/Enhanced-Celestials#198]
### Minecraft Version

1.19.2

### Enhanced Celestials Version

5.0.0.2

### Mod Loader

Forge

### Mod Loader Version

Neoforge 47.1.101

### What happened?

Running Enhanced Celestials with Botania and Mekanism causes the game to crash while launching unreliably.

(This is for Minecraft 1.20.1, but that's not in the dropdown)

Reported on the Botania Github too; https://github.com/VazkiiMods/Botania/issues/4607

### crash-log

https://gist.github.com/LeakingAmps/b890779f20ce349e4295843ab178c7e6

### latest.log

https://paste.ee/p/kGR3n

**Comment by Mysticpasta1** [comment]
this is fixed in the newest botania
