### ISSUE TITLE
[FEATURE SUGGESTION] Config option for bloodmoon every few days

### ISSUE THREAD

**Issue by Zassss** [CorgiTaco/Enhanced-Celestials#2]
Not sure if this is the right place to post this, but can you make a config option so instead of a moon occuring randomly on some nights it happens on a fixed interval (ex every 3 nights) like in the original bloodmoon mod?

 Also, really love the mod, so glad to have bloodmoons on forge 1.16!

**Comment by EnterFor** [comment]
I also want this feature and hope the author will consider it

**Comment by CorgiTaco** [comment]
Added here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430183
