### ISSUE TITLE
Suggestion: 1.20.4 Update?

### ISSUE THREAD

**Issue by EfficientStinkbug** [CorgiTaco/Enhanced-Celestials#200]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

/

### Mod Loader

Fabric

### Mod Loader Version

/

### Bug Severity

Minor

### What happened?

Sorry for making an issue, but there is no other way to make this suggestion :)
Would you maybe consider updating to 1.20.4 fabric? Thanks in advance!

### latest.log

/

**Comment by CorgiTaco** [comment]
@EfficientStinkbug Not interested in supporting non major modded versions due to my lack of time to mod, sorry. It took me 7 months to get to this issue 😩
