### ISSUE TITLE
[Enhancement]: Add a config to increase chances for a certain moon to happen each night.

### ISSUE THREAD

**Issue by Acenthus** [CorgiTaco/Enhanced-Celestials#204]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Bug Severity

Minor

### What happened?

Real quick just wanna mention you guys have enhancement as a tag but only a crash report and bug report option. I'm working on a modpack that makes the night extremely hostile and I'd like for blood moons to happen almost every night without the use of command blocks. TMK this currently isn't possible and it'd be nice to have the option to configure that.

### latest.log

N/A

**Comment by Not-February** [comment]
Pretty sure you should be able to do this with a data pack, there's a field in each file related to the lunar events for the chance of it occurring and changing the minimum nights between the same lunar event happening again.

**Comment by CorgiTaco** [comment]
@Not-February Correct!

**Comment by CorgiTaco** [comment]
Wiki explains that here: https://github.com/CorgiTaco/Enhanced-Celestials/wiki
