### ISSUE TITLE
[Crash]: issue related to LunarForecast

### ISSUE THREAD

**Issue by Atlas-Maker** [CorgiTaco/Enhanced-Celestials#206]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### What happened?

this crash is only happening on a server and is mainly happening on server start up but when I do get a world to load it'll crash if the lunar forecast command is used

it's a mod incompatibility from what I can tell

### crash-log

[crash-2024-06-01_22.59.38-server.txt](https://github.com/user-attachments/files/15524185/crash-2024-06-01_22.59.38-server.txt)

### latest.log

[latest.log](https://github.com/user-attachments/files/15524192/latest.log)

**Comment by CorgiTaco** [comment]
If this is a mod incompatibility you should probably list which mod is causing the incompatibility. Regardless, if the issue persists in 1.21 feel free to open an issue but 1.20 and lower versions will no longer be supported due to the lack of time I have for working on my mods.
