### ISSUE TITLE
[Suggestion]: Lunar events should be longer

### ISSUE THREAD

**Issue by polykatt** [CorgiTaco/Enhanced-Celestials#207]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Bug Severity

Minor

### What happened?

The blood moon event ends at 02:00 in-game time. I feel like this might be a bit too early. After this time the player is allowed to sleep till 06:00 when the sun comes up. I think 06:00 would be a better time to end the event

Or at least allow a config option to alter the duration of lunar events (as well as altering the chances of each occurring would be a great addition).

### latest.log

https://gist.github.com/

**Comment by CorgiTaco** [comment]
@polykatt I will say Im personally happy with how it is currently and it uses the vanilla checks for day and night in code, adding this type of configuration would add a lot of boiler plate imo
