### ISSUE TITLE
[Bug]: Harvest Moon duplicates placed seeds.

### ISSUE THREAD

**Issue by MynxOne** [CorgiTaco/Enhanced-Celestials#208]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

1.20.1-5.0.0.4

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Bug Severity

Major

### What happened?

During the harvest moon (and presumably scaling during the super harvest moon), seeds placed can just be broken again for two seeds. With Pam's HarvestCraft 2, this enables duplication of crops to direct plant drops. This issue works with default vanilla crops as well. A datapack made was also ignored, altering the bonus value for the moon to 0 in order to bypass.

**Comment by MynxOne** [comment]
A found datapack fixed it, sorry for reporting!

**Comment by DarianLStephens** [comment]
What datapack?
Don't just leave us hangin'!

**Comment by MynxOne** [comment]
At first, I tried a datapack consisting of only amendments to harvest and super harvest moons. It didn't seem to work. Then I tried a reload schedule with a variety of changes and this resulted in the values remaining the same minus the value of:

"#enhancedcelestials:harvest_moon_crops":

Which is default 1, which doubles the seed drop count no matter what stage the crop is grown at. If yo uremove the data section containing this value, the server-side will not boot as the datapack causes a load crash. Otherwise, amending the value is a workaround.

**Comment by MynxOne** [comment]
My conclusion: The harvest moon (including super variant) does not check crop growth percentage when harvesting.

**Comment by StrikerDeer** [comment]
Do you have a link to a download of the datapack?

**Comment by MynxOne** [comment]
I ended up making a custom one! Hope this helped:
[EnhancedCelestialsFix.zip](https://github.com/user-attachments/files/15983477/EnhancedCelestialsFix.zip)

**Comment by StrikerDeer** [comment]
Thanks!

**Comment by TheGoldenKnight** [comment]
I cannot get that datapack work @MynxOne.
I play on 1.20.1 with a bunch of other mods. I have tried everything to fix that Harvest moon now and it is crusial that it is fixed for my modpack, plz help

**Comment by CorgiTaco** [comment]
@MynxOne I will say this is intentionally by design. Various crops from different mods use different age blockstate properties and checking if a crop is done growing would be too much hassle
