### ISSUE TITLE
[Bug]: All entities recieve Luck effect on Blue Moon

### ISSUE THREAD

**Issue by Camawama** [CorgiTaco/Enhanced-Celestials#209]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Bug Severity

Major

### What happened?

![image](https://github.com/CorgiTaco/Enhanced-Celestials/assets/43620900/c35c68c9-2056-48d4-8558-e2026f3f8244)

### latest.log

[latest.log](https://github.com/user-attachments/files/15832004/latest.log)

**Comment by Camawama** [comment]
I guess it may be intended but it doesn't feel right.

**Comment by CorgiTaco** [comment]
Ima say for this it's okay lol

**Comment by Camawama** [comment]
Understandable but if I use a datapack to add a potion effect for just players, is that possible or no?

**Comment by CorgiTaco** [comment]
@Camawama You can change the entity filter for the effect like seen [here](https://github.com/CorgiTaco/Enhanced-Celestials/wiki/Mob-Effect) with any of [these](https://github.com/CorgiTaco/Enhanced-Celestials/wiki/Entity-Filters) via datapacks
