### ISSUE TITLE
[Crash]: lighting or something 

### ISSUE THREAD

**Issue by fish034** [CorgiTaco/Enhanced-Celestials#211]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### What happened?

lighting error or something idk but its in the "caused by:" section 

### crash-log

https://gist.github.com/fish034/1b273d97772298e9e7543a88f9baa319

### latest.log

https://gist.github.com/fish034/e9543d8884a6b1fa0a9365ec2d50c475

**Comment by CorgiTaco** [comment]
@fish034 Remove optifine and use one of the newer alternatives like oculus
