### ISSUE TITLE
[Crash]: Crash on start due to CorgiLib

### ISSUE THREAD

**Issue by Eclipse-Sol** [CorgiTaco/Enhanced-Celestials#213]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Fabric

### Mod Loader Version

0.16.0

### What happened?

Game crashes on start now when using the latest version of CorgiLib (Version 4.0.2.0). Downgrading to 4.0.1.3 solves this issue.

### crash-log

https://mclo.gs/IGG3sak

### latest.log

https://mclo.gs/IeQQsOa

**Comment by YOUNIN15** [comment]
I confirm, it used to work fine before, but after the CorgiLib update it no longer works.

**Comment by rmyj** [comment]
same here

**Comment by DefinitelyNotFred** [comment]
Same

**Comment by Happy1speed** [comment]
Seems that CorgiLib had a big rewrite and enhanced celestials hasn't been updated to work with it.

**Comment by Eclipse-Sol** [comment]
Looks like there was a recent update that resolves this issue, now marking this as completed
