### ISSUE TITLE
[Bug]: Blood moon visual effects does not work when certain shaders are used

### ISSUE THREAD

**Issue by lihaan** [CorgiTaco/Enhanced-Celestials#214]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.0.4

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Bug Severity

Minor

### What happened?

When a blood moon happens (I did not test other moons), and the player has Complementary or BSL shaders, the user's screen is not tinted red.

This is quite immersion-breaking as the text appears on screen that a blood moon is occurring, but the player is just left confused and wondering what exactly is going on, instead of getting the much-needed visual cues from the reddish tint that a blood moon brings. (For BSL, the moon at least changes colour slightly.) Disabling shaders brings the visual effects back.

Are there alternative visual effects that are compatible with shaders that can still strike fear and adrenaline into players?

### latest.log

-

**Comment by CorgiTaco** [comment]
Nothing I can do as shader mods like optifine and iris provide absolutely no api.
