### ISSUE TITLE
not configured

### ISSUE THREAD

**Issue by zc1108aaa** [CorgiTaco/Enhanced-Celestials#215]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

0

### Mod Loader

Forge

### Mod Loader Version

0

### Bug Severity

Major

### What happened?

It takes over 100 days to trigger an event
Suggest increasing the probability of configuration adjustment

### latest.log

0

**Comment by CorgiTaco** [comment]
@zc1108aaa /ec lunarforecast recompute should fix it. Sometimes the forecast is a little silly
