### ISSUE TITLE
[Bug]: Harvest Moon not working

### ISSUE THREAD

**Issue by nitbe** [CorgiTaco/Enhanced-Celestials#216]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

forge

### Bug Severity

Major

### What happened?
Harvest Moon not working and super moon too

![@$6%H} ~8(77CKR{_PW~98S](https://github.com/user-attachments/assets/2e84278c-18e2-4620-838b-fb06b6d357ff)

### latest.log

[latest.log](https://github.com/user-attachments/files/16735449/latest.log)

**Comment by nitbe** [comment]
still no working
in 1.20.1-5.0.1.0

**Comment by CorgiTaco** [comment]
@nitbe I checked the drops of crops and it certainly works for any of the following crops included the following modloader/vanilla tags:

![image](https://github.com/user-attachments/assets/a3f17b58-1309-485c-a86e-661522cf47d9)
