### ISSUE TITLE
[Bug]: server hang on stop command

### ISSUE THREAD

**Issue by Fireeyeeian** [CorgiTaco/Enhanced-Celestials#218]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.1.0

### Mod Loader

Fabric

### Mod Loader Version

0.16.5

### Bug Severity

Minor

### What happened?

The server hangs up after issuing the stop command, and you must close the server cmd window in order to actually stop the server.
The server seems to run fine, and the only issue is not stopping with stop command (I haven't joined the server yet, but the stop issue is all I have had a chance to work on atm)

**Downgrading both Enhanced Celestials Version "`5.0.1.0`" to "`5.0.0.4`" and CorgiLib version "`4.0.3.2`" to "`4.0.0.4`" fixes the issue.**
Video showing issue and fix:
[Ec-Cl Bug.webm](https://github.com/user-attachments/assets/5052db0e-804e-4928-bd62-f20ae87d5d60)
(latest.log is of issue happening)
If left waiting for something to happen after the stop command, eventually I got an error or notice stating: "`No captured server found for dedicated server environment, assuming offline mode`" 

For now, I'll just run the version pair that works as I'm ok with that, but I thought I might pass on this information/bug.

### latest.log

[latest.log](https://github.com/user-attachments/files/16973536/latest.log)

**Comment by CorgiTaco** [comment]
This issue was an issue in corgilib which has since been resolved be sure to update corgilib!
