### ISSUE TITLE
[Bug]: Optifine incompability

### ISSUE THREAD

**Issue by epokuser** [CorgiTaco/Enhanced-Celestials#219]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

latest

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Bug Severity

Major

### What happened?

The game crashes with optifine due to Enhanced Celestials and the LightTexture method in this mod!

### latest.log

no

**Comment by CorgiTaco** [comment]
Please use an optifine alternaitve. Optifine will never work with this mod sadly

**Comment by epokuser** [comment]
why not simply use resource packs for replacing moon instead of messing with render

**Comment by CorgiTaco** [comment]
I mess with rendering so the moon color changes with any custom resource pack moons without having to make a new texture every time
