### ISSUE TITLE
[Crash]: Crash Happened after Attempting to Enable Lunar Events for a Mod Dimension by Editing the JAR

### ISSUE THREAD

**Issue by p0rt39** [CorgiTaco/Enhanced-Celestials#222]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.1.0

### Mod Loader

Forge

### Mod Loader Version

47.2.23

## What Version am I Using?
I'm using the latest version avalilable for 1.20.1Forge on Modrinth of Corgilib(4.0.3.2) and EnhancedCelestials(5.0.1.0).
## What Did I do?
I edited the jar pack according to enable lunar events in a mod-added dimension refering to https://github.com/CorgiTaco/Enhanced-Celestials/wiki/Editing-Lunar-Dimension-Settings#data-pack-file-path-examples . 
The JAR I Edited:
[BOTH_Enhanced-Celestials-Forge-1.20.1-5.0.1.0.zip](https://github.com/user-attachments/files/17609541/BOTH_Enhanced-Celestials-Forge-1.20.1-5.0.1.0.zip)
## What's the Result?
The server crash immediately when a player attempts to join in the game with a error of IndexOutOfBoundsException(Exception ticking world).
## Any Tests Have I Done?
I believe it's a mod issue because I tested in both Hybrid Server "Mohist" and my own singleplayer world.
I tested it with:
a **The Aether** dimension *(Mentioned as a successful supported example in the wiki tutorial)* on server,
a **multiverse-core** dimension *(a plugin,not a forge mod,which can create dims under the namespace of minecraft.Github Link:https://github.com/Multiverse/Multiverse-Core)* ,
a **el_adv_dim** dimension *(a mod simply adding a dim like the overworld that I created with MCreator,the mod el_adv_dim appeared in the crash report below)* ,
all of them resulted in crashes and the problem appeared just to be the same.
## Some Additional Details?
My client loaded Sinytra Connect for some extra visual effects,and it can't be blamed for the crash.
The server is a Hybrid Server I know,but the same problem also exists in SinglePlayer pure forge server environment,so it can't be the reason.

### crash-log

[crash-2024-11-03_13.59.51-client.txt](https://github.com/user-attachments/files/17609492/crash-2024-11-03_13.59.51-client.txt)
PS.This log is generated in a single player world,with el_adv_dim loaded.

### latest.log

[latest.log](https://github.com/user-attachments/files/17609491/latest.log)
PS.This log is generated in a single player world,with el_adv_dim loaded.

**Comment by CorgiTaco** [comment]
Make a data pack and do not edit files in the jar. Additionally Sinytra is a buggy mess.
