### ISSUE TITLE
[Bug]: Shows empty message in chat even if notification type is NONE

### ISSUE THREAD

**Issue by hserranome** [CorgiTaco/Enhanced-Celestials#223]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.1.0

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Bug Severity

Minor

### What happened?

Even if notification type is NONE, there still shows an empty message in the chat.
I've tried setting is as type NONE, removing the fields entirely, and leaving them as empty objects, with the same result.

<img width="1247" alt="Screenshot 2024-12-02 at 23 10 32" src="https://github.com/user-attachments/assets/351b3463-08b9-462d-9f7c-af7fa1f2c48d">

<img width="462" alt="Screenshot 2024-12-02 at 23 10 49" src="https://github.com/user-attachments/assets/0661a197-0448-44b8-bc56-c1e4277d5ec8">

```
{
	"client_settings": {
		"color_settings": {
			"moon_texture_color": "990000",
			"sky_light_color": "990000"
		},
		"moon_size": 20.0,
		"moon_texture_location": "minecraft:textures/environment/moon_phases.png",
		"sound_track": {
			"sound_id": "enhancedcelestials:blood_moon"
		}
	},
	"dimension_chances": {
		"minecraft:overworld": {
			"chance": 0.0,
			"min_number_of_nights_between": 4,
			"valid_moon_phases": [0, 1, 2, 3, 4, 5, 6, 7]
		}
	},
	"drops": {
		"drop_enhancer": {}
	},
	"mob_settings": {
		"blocks_sleeping": {
			"type": "corgilib:any"
		},
		"lunar_spawn_settings": {
			"force_surface_spawning": true,
			"mob_spawn_settings": {
				"spawn_costs": {},
				"spawners": {
					"ambient": [],
					"axolotls": [],
					"creature": [],
					"misc": [],
					"monster": [],
					"underground_water_creature": [],
					"water_ambient": [],
					"water_creature": []
				}
			},
			"slimes_spawn_everywhere": false,
			"use_biome_spawn_settings": true
		},
		"mob_effects": [],
		"spawn_category_multiplier": {
			"monster": 2.25
		}
	},
	"text_components": {
		"name": {
			"key": "enhancedcelestials.name.blood_moon",
			"style": {
				"color": "ff5555"
			}
		},
		"start_notification": {
			"type": "NONE"
		},
		"end_notification": {
			"type": "NONE"
		}
	}
}
```

### latest.log

[latest.log](https://github.com/user-attachments/files/17984547/latest.log)

**Comment by CorgiTaco** [comment]
Due to the lack of time I will no longer be supporting versions of this mod that are 1.20 and lower. Apologies for the inconvenience.
