### ISSUE TITLE
[Bug]: most likely incompatibility issue with other mods

### ISSUE THREAD

**Issue by NotYourLifeline** [CorgiTaco/Enhanced-Celestials#224]
### Minecraft Version

1.20.1

### Enhanced Celestials Version

5.0.1.0

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Bug Severity

Major

### What happened?

crash on startup.

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

modlist:
![2024-12-09_04 23 33](https://github.com/user-attachments/assets/bf295a37-1db3-434a-8623-1a580c417c3d)

also Jaden's Nether Expansion causes the crash as well, and the game runs normally without problem when both Enhanced Celestials and Nether Expansion are disabled.

### latest.log

[crash-2024-12-09_04.12.28-client.txt](https://github.com/user-attachments/files/18053646/crash-2024-12-09_04.12.28-client.txt)

**Comment by CorgiTaco** [comment]
Due to the lack of time I will no longer be supporting versions of this mod that are 1.20 and lower. Apologies for the inconvenience.
