### ISSUE TITLE
[SHADERS] Issue when having shaders enabled

### ISSUE THREAD

**Issue by Klinker195** [CorgiTaco/Enhanced-Celestials#23]
Hi! I don't know if this is actually an issue you can fix but when having shaders enabled the sky doesn't become red. If an actual fix is not possible you could add a chat message that warn you that a Blood Moon is rising, same thing with Harvest Moon.
In any case, thank you for your work!

**Comment by CorgiTaco** [comment]
Chat msg is available in latest
