### ISSUE TITLE
Blood Moons Ignore Mob Spawning Rules

### ISSUE THREAD

**Issue by Yourname942** [CorgiTaco/Enhanced-Celestials#25]
MC 1.16.5
Forge 36.0.48
Enhanced Celestials 1.0.1-1.16.4
Torchmaster 2.3.6

When a Blood Moon occurs mobs are ignoring  things that prevent mobs from spawning in areas: Mega Torch from Torchmaster prevents mobs from spawning within 64 block radius by default, however this still happens:
![2021-03-21_08 16 36](https://user-images.githubusercontent.com/58750222/111904660-64d0f580-8a1e-11eb-9d11-7e292672a443.png)
![2021-03-21_08 16 39](https://user-images.githubusercontent.com/58750222/111904661-66022280-8a1e-11eb-9275-b984d0f673ed.png)
![2021-03-21_08 16 54](https://user-images.githubusercontent.com/58750222/111904663-67334f80-8a1e-11eb-8e92-ab0876e52169.png)

**Comment by CorgiTaco** [comment]
I doubt this heavily as all i do in EC is mixin the value of the spawn cap(just change the number). If they do other stuff away from the spawn cap that's a pretty big issue

**Comment by Yourname942** [comment]
The issue isn't the amount of mobs, but rather that they are spawning in areas where they should not be spawning.
