### ISSUE TITLE
[1.16.5] Server Starting Event debug message shown in log

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/Enhanced-Celestials#27]
During server startup, the following message is shown in the log:  
`[corgitaco.enchancedcelestials.EnhancedCelestials/]: Enhanced Celestials: "Server Starting" Event Complete!`   
This seems like a debug message that should not be shown in the regular log, as it is redundant with the regular "Done" message printed by the server.

**Comment by CorgiTaco** [comment]
This is a logger relevant to us and any crash reports that may occur as it lets us know or anyone else know if our event managed to fire/finish. So we're keeping it
