### ISSUE TITLE
Red clouds not visible on server.

### ISSUE THREAD

**Issue by JeremyGreen8** [CorgiTaco/Enhanced-Celestials#29]
I set up a fabric server, and when the mod runs, the mob spawn does absolutely go up, I have around 2k mobs absolutely ravaging the game, but the cloud and the moon and everything is the same, they don't turn red.

The mod is working, but the client doesn't seem to see the red sky.

**Comment by wiidotmom** [comment]
I'm also having this issue with lunar events not being shown on the client (even though the effects are happening on the server). Works fine in singleplayer but not on a server. Fabric API 0.33.1, 1.16.5

**Comment by CorgiTaco** [comment]
This is due to Fabric breaking their network

**Comment by Wachecheiro** [comment]
the same problem here in singleplayer, I have not tried it on server yet, the mod works, spawns mobs fine, but the clouds and moon do not work, the only way that the red tente has appeared is to travel to the nether, return, and there the color of the sky works correctly, and it doesn't always work.

**Comment by CorgiTaco** [comment]
Red clouds are removed
