### ISSUE TITLE
[API Request] Please create and include an API package for other mods to interact with

### ISSUE THREAD

**Issue by zlainsama** [CorgiTaco/Enhanced-Celestials#3]
I have a mod that previously interact with another mod that adds BloodMoon event.
I would like to be able to have a stable way to know if a LunarEvent is happening, currently it is possible to get the LunarEvent from the main Mod class.

**Comment by Urkaz** [comment]
Hi, I don't know if this is still WIP or something, but I'm trying to made my mod interact with Enhanced Celestials too and I don't see a way to identify the type of the current event.

On the Json files I've seen this variable `"type": "enhancedcelestials:blood_moon"`, but I don't see it anywhere on the LunarEvent (there is a `getKey` but it returns something different).

**Comment by zlainsama** [comment]
@Urkaz 
This is the way I have been doing. ([link](https://github.com/zlainsama/PeacefulSurface/blob/99d655db5a790ce4ffbd77f947ca3d75c9ce9701/src/main/java/lain/mods/peacefulsurface/impl/forge/ForgeWorldObj.java#L112-L113))
I have no response from anyone of this mod, you are on your own.
