### ISSUE TITLE
Resource pack support or bug fix???

### ISSUE THREAD

**Issue by Winddbourne** [CorgiTaco/Enhanced-Celestials#33]
Version - 1.0.3-1.16.4

![2021-04-04_14 53 44](https://user-images.githubusercontent.com/24589533/113518814-9b4a5c80-9556-11eb-901d-7b9dc92234fb.png)

As you can see this is supposed to be a harvest moon, but it looks perfectly normal even if I think my custom moon is amazing. My first thought was "My texture pack doesn't support this mod, I should fix that" . . . so I opened up your Jar file and went to Assets to find out what changes I might need to make to add in a blood moon and harvest moon image and whether I'd have to make a separate file for compatibility. 

I didn't find any assets I could support. So I'm guessing that you are doing something in your code to specifically change the color of the default picture, and for whatever reason it's not working with my texture pack. You can find that pack here:

https://www.curseforge.com/minecraft/texture-packs/clear-skyblocks

I'm not sure if the problem I'm finding is a bug for this version, or if the mod never supported resource packs that replace the standard sun and moon, but I wanted to report it either way . . . either as a bug or suggestion. lol

**Comment by CorgiTaco** [comment]
Works for me: 
![Jre-legacy Screenshot 2021 04 04 - 12 13 01 60](https://user-images.githubusercontent.com/66983020/113519131-38010000-953f-11eb-8e42-2f4554f9b7bb.png)

**Comment by CorgiTaco** [comment]
Harvest moon too
![Jre-legacy Screenshot 2021 04 04 - 12 14 08 34](https://user-images.githubusercontent.com/66983020/113519141-46e7b280-953f-11eb-8d62-b8122a312b19.png)

**Comment by CorgiTaco** [comment]
If you're using astral sorcery, there's an issue where they overwrite the entire skybox

**Comment by Winddbourne** [comment]
Ah, that makes sense, I do have astral sorcery in my mod pack. :)

**Comment by Terra-B-Welch** [comment]
apologies for gravedigging this, but has this been tested with astral sorcery set to the fast render option? I.E. Only render the constellations but otherwise keep the vanilla skybox?
