### ISSUE TITLE
BUG - Harvest Moon - Server Crash

### ISSUE THREAD

**Issue by heilong-studios** [CorgiTaco/Enhanced-Celestials#35]
While I and my friend were playing it, once the harvest moon appeared (first and only one, we only had the other one) I no longer could mine blocks and would cause a server crash not sure what is happening. 

[crash-2021-04-06_22.21.51-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/6269891/crash-2021-04-06_22.21.51-server.txt)

**Comment by ghost** [comment]
Based on how many mods you have it's no small chance that some other mod is breaking this. You should binary search for the mod that is potentially conflicting with EC (disable half at a time, see which half needs investigating, rinse and repeat).

**Comment by CorgiTaco** [comment]
Should be fixed here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430183

Reopen this report if the issue persists
