### ISSUE TITLE
Crash on Melon Growth during Harvest Moon?

### ISSUE THREAD

**Issue by Slither88** [CorgiTaco/Enhanced-Celestials#4]
Hi I am using enhancedcelestials-1.0-1.16.4 and forge 35.1.37 and we just had a harvest moon and the server crashed. Here are the logs.
[crash-2021-01-27_15.36.31-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/5880911/crash-2021-01-27_15.36.31-server.txt)

**Comment by CorgiTaco** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3183710
