### ISSUE TITLE
[Suggestion] Separate option for "moon is setting..." notification

### ISSUE THREAD

**Issue by MarioSMB** [CorgiTaco/Enhanced-Celestials#41]
It would be nice to be able to independently disable the "X moon is setting..." notification while keeping the "X moon is rising..." notification, for a couple of reasons: as a nod to Terraria, and for those who do find ways to skip nights (sleeping during a harvest moon, time speedups with Eidolon or vanilla time commands etc).  
In my personal opinion, it is also a tad redundant; players will know the lunar event has ended when it is no longer nighttime.

**Comment by CorgiTaco** [comment]
Added here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430183
