### ISSUE TITLE
Game Crashes when attempting to load a world with Respawnable Animals installed

### ISSUE THREAD

**Issue by NJL5390** [CorgiTaco/Enhanced-Celestials#5]
Hi,
When testing a modpack I've been putting together I added a mod called "Respawnable Animals" to the mod list and whenever I loaded or created a world with that mod installed the game would crash pretty quickly.

After a bit of testing I narrowed down the mod list and found that the crash only occurred when Enhanced Celestials and Respawnable Animals were installed at the same time. Some details about versions and the logs and crash report can be found below:

Minecraft Version: 1.16.5
Forge version: 36.0.7
Enhanced Celestials version: 1.0.1
Respawnable Animals version: 1.0-1

Latest game log:
[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/5884050/latest.log)

Crash Report:
[crash-2021-01-28_00.41.11-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/5884052/crash-2021-01-28_00.41.11-server.txt)

Let me know if you need anything else from me and I'll try to respond as soon as I can.
Thanks!
(Here's a link to the same issue on their github page: https://github.com/Fuzss/respawnableanimals/issues/2)

**Comment by BugmanBugman** [comment]
Getting this too

**Comment by CorgiTaco** [comment]
Patched in their latest version
