### ISSUE TITLE
[suggestion] add an option to change certain messages

### ISSUE THREAD

**Issue by isaacrules2010** [CorgiTaco/Enhanced-Celestials#50]
The current "cannot sleep" message feels too robotic, and i think it would be cool if there were possibly a config to either change that ourselves or have pre-made, more "natural" messages. 
Something as simple as "You cannot sleep during a blood moon"
Or maybe even more flavorful: "All the monsters around make it hard for you to sleep." 
Maybe even just: "You can't sleep right now . . . Good Luck . . . "

**Comment by CorgiTaco** [comment]
You can change this via a lang file with a resource pack

**Comment by CorgiTaco** [comment]
This would be the key: https://github.com/CorgiTaco/Enhanced-Celestials/blob/Forge-1.16.X/src/main/resources/assets/enhancedcelestials/lang/en_us.json#L26
