### ISSUE TITLE
1 out of 10 times red clouds and red moon appear

### ISSUE THREAD

**Issue by Wachecheiro** [CorgiTaco/Enhanced-Celestials#51]
![image](https://user-images.githubusercontent.com/70624279/125704906-ec6e51f3-8c0d-4689-83e8-b292b75c59ab.png)

mod works, spawns mobs fine, but the clouds and moon do not work, the only way that the red tente has appeared is to travel to the nether, return, and there the color of the sky works correctly, and it doesn't always work.

**Comment by CorgiTaco** [comment]
Fixed! https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430183
