### ISSUE TITLE
Game crashes when a Blood moon starts near a village in the latest update

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [CorgiTaco/Enhanced-Celestials#55]
Enhanced Celestials version: 2.0.1
Forge version: 36.2.2
Minecraft Version: 1.16.5
Crash Report: https://gist.github.com/NJL5390/a52e8c8d3dbc64bf99500dc47ac2d830

Hi,

After testing out the latest version of Enhanced Celestials I found that the game crashes after a blood moon starts near a village. This happened after I used a command to start a blood moon manually and after a few seconds the game crashed. The crash report seems to indicate it's something to do with villagers. 

Maybe because they try and sleep at night and then can't during a blood moon the game just crashes because it doesn't know what to do? Feel free to correct me if I'm wrong.

This crash is reproducible without any other mods installed.

I hope this can be addressed soon so that I can do more testing, Thanks for the great mod, it's great to see a mod like this on modern minecraft versions!

**Comment by Yellowbross** [comment]
can confirm this crash has happened to me as well, using forge version 36.1.0. it appears the crash is being caused because something in the blood moon's code is trying to cast the VillagerEntity class to the ServerPlayerEntity class, without properly checking to make sure it's actually an instance of ServerPlayerEntity

**Comment by AllieSniperian** [comment]
Can triple confirm, my game also crashed with a similar issue with villagers "Ticking"

**Comment by CorgiTaco** [comment]
@AllenSniperian @Yellowbross @NJL5390 Fixed it: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430634
