### ISSUE TITLE
Enhanced Celestials incompatiable with Optifabric/Optifine

### ISSUE THREAD

**Issue by aisukuma** [CorgiTaco/Enhanced-Celestials#58]
Seems like some kind of compatibility issue when using Optifabric/Optifine. Having Optifabric/Optifine disabled works when Enhanced Celestials is enabled, but will crash if both mods are enabled.

Using Enhanced Celestials 2.0.2 for Fabric.

[crash-2021-08-22_00.52.57-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/7026610/crash-2021-08-22_00.52.57-client.txt)

**Comment by HazardEST** [comment]
you're using it on 1.17
enhanced celestials is for up to 1.16

also it's a forge mod, not fabric

**Comment by aisukuma** [comment]
There is a fabric mod here:

**Comment by aisukuma** [comment]
There is a fabric version [here](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric).

**Comment by CorgiTaco** [comment]
> 
> 
> you're using it on 1.17
> enhanced celestials is for up to 1.16
> 
> also it's a forge mod, not fabric

both forge + fabric

**Comment by CorgiTaco** [comment]
> 
> 
> Seems like some kind of compatibility issue when using Optifabric/Optifine. Having Optifabric/Optifine disabled works when Enhanced Celestials is enabled, but will crash if both mods are enabled.
> 
> Using Enhanced Celestials 2.0.2 for Fabric.
> 
> [crash-2021-08-22_00.52.57-client.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/7026610/crash-2021-08-22_00.52.57-client.txt)

sadly i dont run the optifabric mod, you'll need to report it to them if it hasnt already been fixed
