### ISSUE TITLE
Incompatible with a lot of mods :(

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/Enhanced-Celestials#59]
Hi, I'm building a mod pack and apparently this mod is incompatible with a lot of mods :(.

Crash report : https://hastebin.com/zupeguyaco.rb

I think that all the mods that have "Error" at the end in the crash report mods list are not working with or are conflicting at the time in the logs they all have a mixin problem.

Once Enhanced Celestials removed I have no more errors :s.

**Comment by CorgiTaco** [comment]
Your crash report is empty therefore this issue is pointless. Try gist.github.com instead

**Comment by ghost** [comment]
No, the crash report is not empty. But if you prefer. https://gist.github.com/PlatiniumOfficial/7fabbd28d92fc5f30f1852faffaafa2d
