### ISSUE TITLE
[Multiple suggestions]Make multiple suggestions 

### ISSUE THREAD

**Issue by EnterFor** [CorgiTaco/Enhanced-Celestials#6]
1.When server is in use
When the Blood Moon arrives, the player will receive a message.
Like: Blood moon coming? ....

2.There are too many monsters spawning during the blood moon. I want this to be configurable
 (I know it's appropriate, but it's a bit too much for me...)

**Comment by GeorgeOrwell1** [comment]
I _definitely_ second this.

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/106575573-247feb80-6534-11eb-9edf-a80bad77b9a7.png)
When I set the Harvest Moon, the information does not display properly

**Comment by CorgiTaco** [comment]
> ![image](https://user-images.githubusercontent.com/10114685/106575573-247feb80-6534-11eb-9edf-a80bad77b9a7.png)
> When I set the Harvest Moon, the information does not display properly

Fixed in latest!

**Comment by CorgiTaco** [comment]
All suggestions listed here have been added
