### ISSUE TITLE
Harvest moon exception while ticking

### ISSUE THREAD

**Issue by Paw-El-Cow** [CorgiTaco/Enhanced-Celestials#60]
Perhaps this is due to the village.

[crash-2021-08-23_14.05.55-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/7031397/crash-2021-08-23_14.05.55-server.txt)

**Comment by LostSoul3471** [comment]
Same issue but with newer 1.17.1 version.
[crash-2021-08-27_23.36.32-server.txt](https://github.com/CorgiTaco/Enhanced-Celestials/files/7070114/crash-2021-08-27_23.36.32-server.txt)
Could be Bagels_Baking but Paw didn't have that mod listed, in fact very little mods in common.

**Comment by CorgiTaco** [comment]
Fixed here:


Forge 1.16: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3443399

-----------------
Fabric 1.16: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/3443395

Fabric 1.17: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric/files/3443397
