### ISSUE TITLE
Conflict with A&D companion mod(outdated class path target)

### ISSUE THREAD

**Issue by Aldentr** [CorgiTaco/Enhanced-Celestials#63]
Playing _Adventures and Dungeons_ modpack for MC 1.16.5 through GDLauncher. Last version of mod **_enhancedcelestials-2.0.6-1.16.5.jar_** conflicts with **_comforts-forge-1.16.5-4.0.1.3.jar_**: game crashing when trying to use sleeping bag, added by **_comforts_**. Tried earlier versions of _**Enhanced Celestials**_, but they crashed game on world loading/creating step. Only _**Enhanced Celestials 1.0.4 MCV: 1.16.4/1.16.5**_ work normal.
Don't know what logfile exactly you need, so attach all, that i find in _logs_ folder.
[debug.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/7073056/debug.log)
[latest.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/7073057/latest.log)
[gottschcore.log](https://github.com/CorgiTaco/Enhanced-Celestials/files/7073058/gottschcore.log)

**Comment by CorgiTaco** [comment]
this isnt comforts fault at all, this is an issue with a mod called "adventuremod"
