### ISSUE TITLE
Harvest Moon is not working as intended

### ISSUE THREAD

**Issue by Muffintiem** [CorgiTaco/Enhanced-Celestials#64]
In Enhanced Celestials 2.0.3 for Minecraft 1.17.1, I'm getting a bug where whenever I try harvesting any crops during a Harvest Moon event, nothing drops. It also doesn't let me obtain wheat seeds from breaking grass. These things happen like normal when it is not a Harvest Moon event.

**Comment by CorgiTaco** [comment]
Send your harvest moon config

**Comment by Muffintiem** [comment]
I copied the contents into pastebin even tho I never changed the configs.

https://pastebin.com/WaUux3xi

I should also probably specify that this is the Fabric version since it's just come to my attention that a Forge version also exists.

**Comment by CorgiTaco** [comment]
try the latest update and lmk if it fixes this

**Comment by Muffintiem** [comment]
It does! Everything is working as it should!
