### ISSUE TITLE
[Bug]: Crash with Create Mod

### ISSUE THREAD

**Issue by Yurinann** [CorgiTaco/Enhanced-Celestials#68]
### Mod Version

2.0.7

### Mod Loader

Forge

### Mod Loader Version

36.2.0

### What happened?

Client crash

### latest.log

https://paste.loliidc.cn/?f3e8b697af715615#3G7oAuM8YWcooWUkpEDaUThAHcTCLDwfYdqczN1uAtxV

**Comment by Griefed** [comment]
Mixin caused problems in versions 2.0.7 and older, but got improved in [2.0.8](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3453410). I've succesfully run version [2.0.8](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3453410) with both Create v0.3.2d and Botania 419 as of 2.0.8.

See whether your crash still occurs with 2.0.8, as you've mentioned that your crash happens with 2.0.7.

**Comment by Yurinann** [comment]
oh i will try. thanks!

**Comment by Yurinann** [comment]
Up to now, there are no corresponding problems. Closed.

Thanks for your help.
