### ISSUE TITLE
[Bug]: Music does not respect sound settings

### ISSUE THREAD

**Issue by milkev** [CorgiTaco/Enhanced-Celestials#70]
### Mod Version

2.0.4 - 1.17.1

### Mod Loader

Fabric

### Mod Loader Version

0.11.6

### What happened?

[The Issue]
When you have your music volume disabled the soundtrack of celestial events is still played at full volume

[The Solution]
Make music soundtracks respect music volume setting

### latest.log

No reason to include

**Comment by CorgiTaco** [comment]
It does. The music functions exactly that of biome music. https://github.com/CorgiTaco/Enhanced-Celestials/blob/Forge-1.16.X/src/main/java/corgitaco/enhancedcelestials/client/LunarSoundHandler.java#L43

Lower the ambient sound volume if you dont like it :D

**Comment by milkev** [comment]
odd thing to bind music too, especially since its not even tied to any biome
thanks though
