### ISSUE TITLE
[Bug]: server crash on start

### ISSUE THREAD

**Issue by BlackcatCXII** [CorgiTaco/Enhanced-Celestials#71]
### Mod Version

2.0.8

### Mod Loader

Forge

### Mod Loader Version

36.2.0

### What happened?

Server crashes on start was working fine a few days ago

### latest.log

https://hastebin.com/tosudidupo.rb

**Comment by iMahco** [comment]
This seems awfully familiar to a crash I was experiencing, good sir would you happen to have any mobs listed in performant's config's **excludedTickDistanceMobs**? Getting rid of the list I had there resolved the crashes on my end.

**Comment by CorgiTaco** [comment]
Your hastebin link is expired. Closing this issue until the log is provided again
