### ISSUE TITLE
[Bug]: Still possible to sleep through Blood Moons with (at least) Upgrade Aquatic's bedroll

### ISSUE THREAD

**Issue by lamoyrl90** [CorgiTaco/Enhanced-Celestials#76]
### Mod Version

2.0.8-1.16.5

### Mod Loader

Forge

### Mod Loader Version

36.2.4

### What happened?

Haven't tested it with other bedlike blocks, but I was able to sleep through a Blood Moon with Upgrade Aquatic's bedroll. No log to provide, just an anecdotal report of unintended behavior.

I'm not sure if it's possible to generically block bed-like behavior. If it's possible, maybe add a "Beds" config option for packmakers to add additional blocks that are restricted during lunar events,

Either way, figured I'd at least give you a heads' up. Worst case, packmakers will have to choose between denying sleep during blood moons, or not letting players get alternative beds.

### latest.log

N/A

**Comment by CorgiTaco** [comment]
It is upgrade Aquatic's duty to use the appropriate checks. In this case Upgrade Aquatic should use `LivingEntity.isInValidBed` to ensure my mod's checks are fired from here: https://github.com/CorgiTaco/Enhanced-Celestials/blob/Forge-1.16.X/src/main/java/corgitaco/enhancedcelestials/mixin/MixinLivingEntity.java#L36

**Comment by lamoyrl90** [comment]
Thanks for the reply. I'll file it on their page.

**Comment by lamoyrl90** [comment]
Oddly enough, after being able to sleep through multiple blood moons it blocked me from using the bedroll during another. *shrug*
