### ISSUE TITLE
[Bug]: Ticking Screen Crash [Create v0.3.2f + Enhanced Celestials 1.0.8]

### ISSUE THREAD

**Issue by Lilwhiteshark** [CorgiTaco/Enhanced-Celestials#77]
### Mod Version

1.0.8

### Mod Loader

Forge

### Mod Loader Version

36.2.8

### What happened?

While Pondering the Deployer (UI component of the Create mod), experiencing a crash when the pink sheep shows up. 

```
Description: Ticking screen

java.lang.ClassCastException: com.simibubi.create.foundation.ponder.PonderWorld cannot be cast to corgitaco.enhancedcelestials.EnhancedCelestialsWorldData
```
Without the Enhanced Celestials mod installed there is no issue. I will also post the full crashlog.

### latest.log

[Ticking Screen Crashlog](https://gist.github.com/Lilwhiteshark/67a130f551c2f8905311c8b005dbedcc)

**Comment by mosharky** [comment]
Same issue here
