### ISSUE TITLE
Server Crash - harvest moon ticking Upgrade_Aquatic log?

### ISSUE THREAD

**Issue by phyne** [CorgiTaco/Enhanced-Celestials#8]
Not entirely sure if I'm right, but it looks like the harvest moon tried to tick an upgrade aquatic log as a sapling or something:

https://gist.github.com/phyne/db96fe6f1be6685ddc9b84286ad096f9

**Comment by CorgiTaco** [comment]
Should be fixed already. I see you're using 1.0. Use 1.0.1 instead: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3183710

**Comment by phyne** [comment]
Domehow missed that version, sorry about that!
