### ISSUE TITLE
Potential compatibility problem

### ISSUE THREAD

**Issue by AmibeSkyfy16** [CorgiTaco/Enhanced-Celestials#80]
### Mod Version

enhancedcelestials-1.17.1-2.0.5.jar

### Mod Loader

Fabric

### Mod Loader Version

0.12.5

### What happened?

i notice that there is no increase in the number of mobs as it should normally be the case.

I think its because im using "Per Player Mob Cap" and "Custom MobCap" Mods. maybe a compatibility problem

### latest.log

https://pastebin.com/TC9txKfp

**Comment by CorgiTaco** [comment]
Therefore these mods are incompatible, ask the mods you listed to add compatibility.
