### ISSUE TITLE
[Suggestion] Config option to only roll for blood/harvest moon on regular full moon nights

### ISSUE THREAD

**Issue by Snowiez** [CorgiTaco/Enhanced-Celestials#9]
I just thought this would make more sense and would also give the player _some_ idea of when a special moon could occur.

**Comment by JoeltCola734** [comment]
I second this. I have a darkness mod on, and really messes with the visuals when it occurs on anything besides a full moon.

**Comment by CorgiTaco** [comment]
Added here: https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials/files/3430183
